# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: myresume_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myresume
    # (this is just an example, not intended to be a production configuration)
    # adminer:
    #   conatiner_name: myresume_adminer
    #   image: adminer
    #   restart : always
    #   ports:
    #     - "8080:8080"
