# Generated by Django 5.1.4 on 2025-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('typed', models.CharField(help_text='Type like -> an Engineer, Project Manager, Yoga Instructor', max_length=255, verbose_name='typed')),
                ('git', models.URLField(verbose_name='github link')),
                ('facebook', models.URLField(verbose_name='facebook link')),
                ('insta', models.URLField(verbose_name='insta link')),
                ('strava', models.URLField(verbose_name='strava link')),
                ('linkedIn', models.URLField(verbose_name='linkedIn link')),
            ],
        ),
    ]
