# Generated by Django 5.1.4 on 2025-06-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='name')),
                ('paragraph', models.TextField(verbose_name='paragraph')),
                ('clients_count', models.IntegerField(default=1, verbose_name='Happy Clients')),
                ('hours_support', models.IntegerField(default=1, verbose_name='Hours support')),
                ('awards', models.IntegerField(verbose_name='Awards')),
            ],
        ),
    ]
